/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestfulAdmin.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    title: 'RESTful Admin Panel',
                    store: 'Users',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'username',
                            text: 'Username'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstName',
                            text: 'First Name',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastName',
                            text: 'Last Name',
                            flex: 1
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'signupDate',
                            text: 'Signup Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            align: 'center',
                            dataIndex: 'enabled',
                            text: 'Enabled',
                            falseText: 'No',
                            trueText: 'Yes'
                        },
                        {
                            xtype: 'actioncolumn',
                            align: 'center',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        console.log(view.up('#userWindow'));

                                        var window = Ext.create('RestfulAdmin.view.UserWindow');
                                        window.down('form').loadRecord(record);
                                    },
                                    icon: 'resources/edit-user-icon-small.jpg'
                                },
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        console.log('deleteUser');
                                        Ext.Msg.confirm('Confirm Delete', 
                                        'Are you sure you want to delete ' + record.get('firstName') + ' ' + record.get('lastName') + '?',
                                        function(buttonId) {
                                            if (buttonId == 'yes') record.destroy();
                                        });
                                    },
                                    icon: 'resources/remove-user-icon-small.jpg'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var window = Ext.create('RestfulAdmin.view.UserWindow');
                                    },
                                    glyph: '',
                                    iconCls: '',
                                    text: 'New User'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});