/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestfulAdmin.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.mainview',

    requires: [
        'RestfulAdmin.view.UserForm'
    ],

    config: {
        layout: {
            animation: 'flip',
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'RESTful Admin'
            },
            {
                xtype: 'container',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        itemId: 'userList',
                        itemTpl: [
                            '<div>{firstName} {lastName}</div>'
                        ],
                        store: 'Users',
                        grouped: true,
                        onItemDisclosure: true
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'newUserButton',
                                iconCls: 'add',
                                text: 'New User'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'userform'
            }
        ]
    }

});