/*
 * File: app/view/UserForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestfulAdmin.view.UserForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.userform',

    config: {
        ui: '',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'saveButton',
                        ui: 'action',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        itemId: 'cancelButton',
                        ui: 'confirm',
                        text: 'Cancel'
                    }
                ]
            },
            {
                xtype: 'textfield',
                label: 'Username',
                name: 'username'
            },
            {
                xtype: 'passwordfield',
                label: 'Password',
                name: 'password'
            },
            {
                xtype: 'textfield',
                label: 'First Name',
                name: 'firstName'
            },
            {
                xtype: 'textfield',
                label: 'Last Name',
                name: 'lastName'
            },
            {
                xtype: 'checkboxfield',
                label: 'Active',
                name: 'enabled'
            },
            {
                xtype: 'button',
                itemId: 'deleteUserButton',
                ui: 'decline',
                text: 'Delete User'
            }
        ]
    }

});