/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RestfulAdmin.model.User', {
    extend: 'Ext.data.Model',

    idProperty: '_id',

    proxy: {
        type: 'rest',
        url: 'http://localhost:3000/users',
        reader: {
            type: 'json',
            root: 'data'
        },
        writer: {
            type: 'json'
        }
    },

    fields: [
        {
            name: 'username'
        },
        {
            name: 'firstName'
        },
        {
            name: 'lastName'
        },
        {
            name: 'signupDate',
            type: 'date'
        },
        {
            name: 'enabled'
        },
        {
            name: '_id',
            type: 'string'
        },
        {
            name: 'password'
        }
    ]
});